# fly.toml app configuration file generated for tennis-doubles on 2024-09-08T13:09:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tennis-doubles'
primary_region = 'lhr'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'
  DJANGO_SETTINGS_MODULE = "tennis_doubles.settings"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[[mounts]]
  source = 'sqlite3'
  destination = '/code/data'

[deploy]
  release_command = 'python manage.py migrate'
  strategy = "immediate"
  startup_timeout = "60s"