# fly.toml app configuration file for tennis-doubles

app = 'tennis-doubles'
primary_region = 'lhr'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'
  DJANGO_SETTINGS_MODULE = "tennis_doubles.settings"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[deploy]
  release_command = 'python manage.py migrate'
  strategy = "immediate"
  startup_timeout = "60s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[[mounts]]
  source = 'sqlite3'
  destination = '/code/data'

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000

[[processes]]
  name = "app"
  command = "gunicorn tennis_doubles.wsgi"

[[processes]]
  name = "backup"
  command = "python manage.py backup_db"
  schedule = "@daily"