name: Pull Request Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run migrations
      env:
        DEBUG: 'False'
        SECRET_KEY: 'test-secret-key'
        SQLITE_DB_PATH: ':memory:'
      run: |
        python manage.py migrate
    
    - name: Run unit tests
      env:
        DEBUG: 'False'
        SECRET_KEY: 'test-secret-key'
        SQLITE_DB_PATH: ':memory:'
      run: python manage.py test

    - name: Check test results
      if: failure()
      run: |
        echo "Tests failed. This pull request cannot be merged."
        exit 1
